/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Message = IDL.Record({
  'id' : IDL.Nat,
  'to' : IDL.Text,
  'color' : IDL.Text,
  'song' : IDL.Text,
  'isPrivate' : IDL.Bool,
  'message' : IDL.Text,
  'timestamp' : IDL.Int,
  'isSeeded' : IDL.Bool,
});

export const idlService = IDL.Service({
  'getMessages' : IDL.Func([], [IDL.Vec(Message)], ['query']),
  'searchMessages' : IDL.Func([IDL.Text], [IDL.Vec(Message)], ['query']),
  'submitMessage' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Bool],
      [IDL.Nat],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Message = IDL.Record({
    'id' : IDL.Nat,
    'to' : IDL.Text,
    'color' : IDL.Text,
    'song' : IDL.Text,
    'isPrivate' : IDL.Bool,
    'message' : IDL.Text,
    'timestamp' : IDL.Int,
    'isSeeded' : IDL.Bool,
  });
  
  return IDL.Service({
    'getMessages' : IDL.Func([], [IDL.Vec(Message)], ['query']),
    'searchMessages' : IDL.Func([IDL.Text], [IDL.Vec(Message)], ['query']),
    'submitMessage' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Bool],
        [IDL.Nat],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };